# Generated by Django 6.0.1 on 2026-02-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
